[package]
name = "aws-wire-lengths"
version = "0.1.0"
authors = ["Joshua M. Clulow <josh@sysmgr.org>"]
edition = "2018"

[features]
default = ["vendored-openssl"]
vendored-openssl = ['openssl/vendored']

[dependencies]
rusoto_core = "0.46.0"
rusoto_ec2 = "0.46.0"
rusoto_s3 = "0.46.0"
rusoto_credential = "0.46.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.4"
xml-rs = "0.8"
getopts = "0.2"
bytes = "1"
futures = "0.3"
tokio-util = { version = "0.6", features = [ "io", "codec" ] }
rand = "0.8"

#
# I believe it is necessary to pull this in here, so that we can demand the
# static linking of the vendored OpenSSL.  We don't use it directly, but the
# same version will then be used by reqwest.
#
openssl = { version = "0.10", optional = true }
